source 'https://github.com/JakyHao/PPSpecs.git'
source 'hppts://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'PPUserKit_Example' do
  pod 'PPUserKit', :path => '../'

  target 'PPUserKit_Tests' do
    inherit! :search_paths

    
  end
end
